image: harbor.duowan.com/ued/kda

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - release

# 安装依赖
before_script:
  - yarn config set registry https://npm-registry.duowan.com

# 构建 - 测试环境
build_test:
  stage: build
  tags:
    - yyci_office
  only:
    - test
  artifacts:
    expire_in: 1 week
    paths:
    - dist
    - package.json
  script:
    - yarn install
    - npm run build:test

# 构建 - 生产环境
build_prod:
  stage: build
  tags:
    - yyci_office
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
    - dist
    - package.json
  script:
    - yarn install
    - npm run build:prod

# 发布 - 测试环境
release_test:
  only:
    - test
  stage: release
  tags:
    - yyci_office
  script:
    - yarn global add @yy/rv-cli
    - rv dist --ignoreNotice

# 发布 - 生产环境
release_prod:
  when: manual
  only:
    - master
  stage: release
  tags:
    - yyci_office
  script:
    - yarn global add @yy/rv-cli
    - rv dist --ignoreNotice
